#!/bin/sh
# cleanup
rm -rf obj_dir
rm -r Vsinegen.vcd


# run Verilator so we can translate .sv into .cpp, and pass this to our C++ testbench


verilator -Wall --cc --trace sinegen.sv rom.sv counter.sv --exe sinegen_tb.cpp

#build the C++ project through make automatically generated by verilator

make -j -C obj_dir/ -f Vsinegen.mk Vsinegen 

#run the executable simulation file

obj_dir/Vsinegen


