#!/bin/sh
# cleanup
rm -rf obj_dir
rm -r Vlfsr_7b.vcd


# run Verilator so we can translate .sv into .cpp, and pass this to our C++ testbench


verilator -Wall --cc --trace lfsr_7b.sv --exe lfsr_tb.cpp

#build the C++ project through make automatically generated by verilator

make -j -C obj_dir/ -f Vlfsr_7b.mk Vlfsr_7b

#run the executable simulation file

obj_dir/Vlfsr_7b


