#!/bin/sh
# cleanup
rm -rf obj_dir
rm -r Vsigdelay.vcd


# run Verilator so we can translate .sv into .cpp, and pass this to our C++ testbench


verilator -Wall --cc --trace sigdelay.sv ram2ports.sv counter.sv --exe sigdelay_tb.cpp

#build the C++ project through make automatically generated by verilator

make -j -C obj_dir/ -f Vsigdelay.mk Vsigdelay

#run the executable simulation file

obj_dir/Vsigdelay


